#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tracker
Version  : 1.12.3
Release  : 1
URL      : https://download.gnome.org/sources/tracker/1.12/tracker-1.12.3.tar.xz
Source0  : https://download.gnome.org/sources/tracker/1.12/tracker-1.12.3.tar.xz
Summary  : Tracker : A library to perform SPARQL queries and updates in the \
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: tracker-bin
Requires: tracker-config
Requires: tracker-data
Requires: tracker-lib
Requires: tracker-doc
Requires: tracker-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : json-glib-dev
BuildRequires : libexif-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libsoup-dev
BuildRequires : libunistring-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(exempi-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libseccomp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)

%description
1 Introduction
Tracker is a search engine and that allows the user to find their
data as fast as possible. Users can search for their files and
search for content in their files too.

%package bin
Summary: bin components for the tracker package.
Group: Binaries
Requires: tracker-data
Requires: tracker-config

%description bin
bin components for the tracker package.


%package config
Summary: config components for the tracker package.
Group: Default

%description config
config components for the tracker package.


%package data
Summary: data components for the tracker package.
Group: Data

%description data
data components for the tracker package.


%package dev
Summary: dev components for the tracker package.
Group: Development
Requires: tracker-lib
Requires: tracker-bin
Requires: tracker-data
Provides: tracker-devel

%description dev
dev components for the tracker package.


%package doc
Summary: doc components for the tracker package.
Group: Documentation

%description doc
doc components for the tracker package.


%package lib
Summary: lib components for the tracker package.
Group: Libraries
Requires: tracker-data
Requires: tracker-config

%description lib
lib components for the tracker package.


%package locales
Summary: locales components for the tracker package.
Group: Default

%description locales
locales components for the tracker package.


%prep
%setup -q -n tracker-1.12.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505330445
%configure --disable-static --enable-minimal --enable-tracker-fts=no --enable-icu-charset-detection=no
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1505330445
rm -rf %{buildroot}
%make_install
%find_lang tracker

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tracker
/usr/libexec/tracker-store

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/user/tracker-store.service

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Tracker-1.0.typelib
/usr/lib64/girepository-1.0/TrackerControl-1.0.typelib
/usr/lib64/girepository-1.0/TrackerMiner-1.0.typelib
/usr/share/bash-completion/completions/tracker
/usr/share/dbus-1/services/org.freedesktop.Tracker1.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.DB.gschema.xml
/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.Store.gschema.xml
/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.enums.xml
/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.gschema.xml
/usr/share/tracker/ontologies/10-xsd.description
/usr/share/tracker/ontologies/10-xsd.ontology
/usr/share/tracker/ontologies/11-rdf.description
/usr/share/tracker/ontologies/11-rdf.ontology
/usr/share/tracker/ontologies/12-nrl.description
/usr/share/tracker/ontologies/12-nrl.ontology
/usr/share/tracker/ontologies/20-dc.description
/usr/share/tracker/ontologies/20-dc.ontology
/usr/share/tracker/ontologies/30-nie.description
/usr/share/tracker/ontologies/30-nie.ontology
/usr/share/tracker/ontologies/31-nao.description
/usr/share/tracker/ontologies/31-nao.ontology
/usr/share/tracker/ontologies/32-nco.description
/usr/share/tracker/ontologies/32-nco.ontology
/usr/share/tracker/ontologies/33-nfo.description
/usr/share/tracker/ontologies/33-nfo.ontology
/usr/share/tracker/ontologies/34-nmo.description
/usr/share/tracker/ontologies/34-nmo.ontology
/usr/share/tracker/ontologies/35-ncal.description
/usr/share/tracker/ontologies/35-ncal.ontology
/usr/share/tracker/ontologies/36-scal.description
/usr/share/tracker/ontologies/36-scal.ontology
/usr/share/tracker/ontologies/37-nid3.description
/usr/share/tracker/ontologies/37-nid3.ontology
/usr/share/tracker/ontologies/38-nmm.description
/usr/share/tracker/ontologies/38-nmm.ontology
/usr/share/tracker/ontologies/39-mto.description
/usr/share/tracker/ontologies/39-mto.ontology
/usr/share/tracker/ontologies/40-mlo.description
/usr/share/tracker/ontologies/40-mlo.ontology
/usr/share/tracker/ontologies/41-mfo.description
/usr/share/tracker/ontologies/41-mfo.ontology
/usr/share/tracker/ontologies/89-mtp.description
/usr/share/tracker/ontologies/89-mtp.ontology
/usr/share/tracker/ontologies/90-tracker.description
/usr/share/tracker/ontologies/90-tracker.ontology
/usr/share/tracker/ontologies/92-slo.description
/usr/share/tracker/ontologies/92-slo.ontology
/usr/share/tracker/ontologies/93-libosinfo.description
/usr/share/tracker/ontologies/93-libosinfo.ontology
/usr/share/tracker/stop-words/stopwords.da
/usr/share/tracker/stop-words/stopwords.de
/usr/share/tracker/stop-words/stopwords.en
/usr/share/tracker/stop-words/stopwords.es
/usr/share/tracker/stop-words/stopwords.fi
/usr/share/tracker/stop-words/stopwords.fr
/usr/share/tracker/stop-words/stopwords.hu
/usr/share/tracker/stop-words/stopwords.it
/usr/share/tracker/stop-words/stopwords.nb
/usr/share/tracker/stop-words/stopwords.nl
/usr/share/tracker/stop-words/stopwords.pt
/usr/share/tracker/stop-words/stopwords.ru
/usr/share/tracker/stop-words/stopwords.sv
/usr/share/tracker/tracker-backup.xml
/usr/share/tracker/tracker-miner.xml
/usr/share/tracker/tracker-resources.xml
/usr/share/tracker/tracker-statistics.xml
/usr/share/tracker/tracker-status.xml
/usr/share/vala/vapi/tracker-control-1.0.deps
/usr/share/vala/vapi/tracker-control-1.0.vapi
/usr/share/vala/vapi/tracker-miner-1.0.deps
/usr/share/vala/vapi/tracker-miner-1.0.vapi
/usr/share/vala/vapi/tracker-sparql-1.0.deps
/usr/share/vala/vapi/tracker-sparql-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/tracker-1.0/libtracker-control/tracker-control.h
/usr/include/tracker-1.0/libtracker-control/tracker-miner-manager.h
/usr/include/tracker-1.0/libtracker-miner/tracker-data-provider.h
/usr/include/tracker-1.0/libtracker-miner/tracker-decorator-fs.h
/usr/include/tracker-1.0/libtracker-miner/tracker-decorator.h
/usr/include/tracker-1.0/libtracker-miner/tracker-enumerator.h
/usr/include/tracker-1.0/libtracker-miner/tracker-indexing-tree.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner-enum-types.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner-enums.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner-fs.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner-object.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner-online.h
/usr/include/tracker-1.0/libtracker-miner/tracker-miner.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-generated.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-namespace-manager.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-notifier.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-ontologies.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-resource.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-sparql.h
/usr/include/tracker-1.0/libtracker-sparql/tracker-version.h
/usr/lib64/libtracker-control-1.0.so
/usr/lib64/libtracker-miner-1.0.so
/usr/lib64/libtracker-sparql-1.0.so
/usr/lib64/pkgconfig/tracker-control-1.0.pc
/usr/lib64/pkgconfig/tracker-miner-1.0.pc
/usr/lib64/pkgconfig/tracker-sparql-1.0.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
/usr/share/gtk-doc/html/libtracker-control/TrackerMinerManager.html
/usr/share/gtk-doc/html/libtracker-control/annotation-glossary.html
/usr/share/gtk-doc/html/libtracker-control/ch01.html
/usr/share/gtk-doc/html/libtracker-control/home.png
/usr/share/gtk-doc/html/libtracker-control/index.html
/usr/share/gtk-doc/html/libtracker-control/left-insensitive.png
/usr/share/gtk-doc/html/libtracker-control/left.png
/usr/share/gtk-doc/html/libtracker-control/libtracker-control.devhelp2
/usr/share/gtk-doc/html/libtracker-control/libtracker-miner-reference.html
/usr/share/gtk-doc/html/libtracker-control/right-insensitive.png
/usr/share/gtk-doc/html/libtracker-control/right.png
/usr/share/gtk-doc/html/libtracker-control/style.css
/usr/share/gtk-doc/html/libtracker-control/up-insensitive.png
/usr/share/gtk-doc/html/libtracker-control/up.png
/usr/share/gtk-doc/html/libtracker-miner/TrackerDataProvider.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerDecorator.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerDecoratorFS.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerIndexingTree.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerMiner.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerMinerFS.html
/usr/share/gtk-doc/html/libtracker-miner/TrackerMinerOnline.html
/usr/share/gtk-doc/html/libtracker-miner/annotation-glossary.html
/usr/share/gtk-doc/html/libtracker-miner/ch02.html
/usr/share/gtk-doc/html/libtracker-miner/ch03.html
/usr/share/gtk-doc/html/libtracker-miner/ch04.html
/usr/share/gtk-doc/html/libtracker-miner/ch05.html
/usr/share/gtk-doc/html/libtracker-miner/home.png
/usr/share/gtk-doc/html/libtracker-miner/index.html
/usr/share/gtk-doc/html/libtracker-miner/left-insensitive.png
/usr/share/gtk-doc/html/libtracker-miner/left.png
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-Enumerations.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-Media-art-management.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-TrackerEnumerator.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-TrackerFileDataProvider.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-TrackerFileEnumerator.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-TrackerThumbnailer.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner-reference.html
/usr/share/gtk-doc/html/libtracker-miner/libtracker-miner.devhelp2
/usr/share/gtk-doc/html/libtracker-miner/right-insensitive.png
/usr/share/gtk-doc/html/libtracker-miner/right.png
/usr/share/gtk-doc/html/libtracker-miner/style.css
/usr/share/gtk-doc/html/libtracker-miner/tracker-overview-compiling.html
/usr/share/gtk-doc/html/libtracker-miner/tracker-overview.html
/usr/share/gtk-doc/html/libtracker-miner/up-insensitive.png
/usr/share/gtk-doc/html/libtracker-miner/up.png
/usr/share/gtk-doc/html/libtracker-sparql/TrackerNotifier.html
/usr/share/gtk-doc/html/libtracker-sparql/TrackerResource.html
/usr/share/gtk-doc/html/libtracker-sparql/TrackerSparqlBuilder.html
/usr/share/gtk-doc/html/libtracker-sparql/TrackerSparqlConnection.html
/usr/share/gtk-doc/html/libtracker-sparql/TrackerSparqlCursor.html
/usr/share/gtk-doc/html/libtracker-sparql/annotation-glossary.html
/usr/share/gtk-doc/html/libtracker-sparql/home.png
/usr/share/gtk-doc/html/libtracker-sparql/index.html
/usr/share/gtk-doc/html/libtracker-sparql/left-insensitive.png
/usr/share/gtk-doc/html/libtracker-sparql/left.png
/usr/share/gtk-doc/html/libtracker-sparql/libtracker-sparql-TrackerNamespaceManager.html
/usr/share/gtk-doc/html/libtracker-sparql/libtracker-sparql-Utilities.html
/usr/share/gtk-doc/html/libtracker-sparql/libtracker-sparql-Version-Information.html
/usr/share/gtk-doc/html/libtracker-sparql/libtracker-sparql-reference.html
/usr/share/gtk-doc/html/libtracker-sparql/libtracker-sparql.devhelp2
/usr/share/gtk-doc/html/libtracker-sparql/right-insensitive.png
/usr/share/gtk-doc/html/libtracker-sparql/right.png
/usr/share/gtk-doc/html/libtracker-sparql/style.css
/usr/share/gtk-doc/html/libtracker-sparql/tracker-examples-builder.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-examples-readonly.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-examples-writeonly-with-blank-nodes.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-examples-writeonly.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-examples.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-overview-compiling.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-overview-connection-methods.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-overview-environment-variables.html
/usr/share/gtk-doc/html/libtracker-sparql/tracker-overview.html
/usr/share/gtk-doc/html/libtracker-sparql/up-insensitive.png
/usr/share/gtk-doc/html/libtracker-sparql/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtracker-control-1.0.so.0
/usr/lib64/libtracker-control-1.0.so.0.1203.0
/usr/lib64/libtracker-miner-1.0.so.0
/usr/lib64/libtracker-miner-1.0.so.0.1203.0
/usr/lib64/libtracker-sparql-1.0.so.0
/usr/lib64/libtracker-sparql-1.0.so.0.1203.0
/usr/lib64/tracker-1.0/libtracker-common.so
/usr/lib64/tracker-1.0/libtracker-common.so.0
/usr/lib64/tracker-1.0/libtracker-common.so.0.0.0
/usr/lib64/tracker-1.0/libtracker-data.so
/usr/lib64/tracker-1.0/libtracker-data.so.0
/usr/lib64/tracker-1.0/libtracker-data.so.0.0.0
/usr/lib64/tracker-1.0/libtracker-extract.so
/usr/lib64/tracker-1.0/libtracker-extract.so.0
/usr/lib64/tracker-1.0/libtracker-extract.so.0.0.0

%files locales -f tracker.lang
%defattr(-,root,root,-)

