#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tracker
Version  : 3.2.0
Release  : 36
URL      : https://download.gnome.org/sources/tracker/3.2/tracker-3.2.0.tar.xz
Source0  : https://download.gnome.org/sources/tracker/3.2/tracker-3.2.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: tracker-bin = %{version}-%{release}
Requires: tracker-data = %{version}-%{release}
Requires: tracker-lib = %{version}-%{release}
Requires: tracker-libexec = %{version}-%{release}
Requires: tracker-license = %{version}-%{release}
Requires: tracker-locales = %{version}-%{release}
Requires: tracker-services = %{version}-%{release}
BuildRequires : bash-completion-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gstreamer-dev
BuildRequires : json-glib-dev
BuildRequires : libexif-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libsoup-dev
BuildRequires : libunistring-dev
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : pygobject
BuildRequires : systemd-dev

%description
The turtle files are created in this directory. For importing them into
tracker use:

%package bin
Summary: bin components for the tracker package.
Group: Binaries
Requires: tracker-data = %{version}-%{release}
Requires: tracker-libexec = %{version}-%{release}
Requires: tracker-license = %{version}-%{release}
Requires: tracker-services = %{version}-%{release}

%description bin
bin components for the tracker package.


%package data
Summary: data components for the tracker package.
Group: Data

%description data
data components for the tracker package.


%package dev
Summary: dev components for the tracker package.
Group: Development
Requires: tracker-lib = %{version}-%{release}
Requires: tracker-bin = %{version}-%{release}
Requires: tracker-data = %{version}-%{release}
Provides: tracker-devel = %{version}-%{release}
Requires: tracker = %{version}-%{release}

%description dev
dev components for the tracker package.


%package lib
Summary: lib components for the tracker package.
Group: Libraries
Requires: tracker-data = %{version}-%{release}
Requires: tracker-libexec = %{version}-%{release}
Requires: tracker-license = %{version}-%{release}

%description lib
lib components for the tracker package.


%package libexec
Summary: libexec components for the tracker package.
Group: Default
Requires: tracker-license = %{version}-%{release}

%description libexec
libexec components for the tracker package.


%package license
Summary: license components for the tracker package.
Group: Default

%description license
license components for the tracker package.


%package locales
Summary: locales components for the tracker package.
Group: Default

%description locales
locales components for the tracker package.


%package services
Summary: services components for the tracker package.
Group: Systemd services

%description services
services components for the tracker package.


%prep
%setup -q -n tracker-3.2.0
cd %{_builddir}/tracker-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632419343
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dfts=false \
-Dfunctional_tests=false \
-Dman=false \
-Ddoc=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/tracker
cp %{_builddir}/tracker-3.2.0/COPYING.GPL %{buildroot}/usr/share/package-licenses/tracker/33fabce185708a9b17df7a9f37c7ed44eddc7e48
cp %{_builddir}/tracker-3.2.0/COPYING.LGPL %{buildroot}/usr/share/package-licenses/tracker/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-3.2.0/src/libtracker-common/COPYING.LIB %{buildroot}/usr/share/package-licenses/tracker/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-3.2.0/src/libtracker-data/COPYING.LIB %{buildroot}/usr/share/package-licenses/tracker/9a1929f4700d2407c70b507b3b2aaf6226a9543c
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang tracker3
## install_append content
#mv %{buildroot}/etc/xdg %{buildroot}/usr/share/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/tracker-3.0/trackertestutils/__init__.py
/usr/lib64/tracker-3.0/trackertestutils/__main__.py
/usr/lib64/tracker-3.0/trackertestutils/dbusdaemon.py
/usr/lib64/tracker-3.0/trackertestutils/dconf.py
/usr/lib64/tracker-3.0/trackertestutils/helpers.py
/usr/lib64/tracker-3.0/trackertestutils/mainloop.py
/usr/lib64/tracker-3.0/trackertestutils/psutil_mini.py
/usr/lib64/tracker-3.0/trackertestutils/sandbox.py
/usr/lib64/tracker-3.0/trackertestutils/storehelper.py
/usr/lib64/tracker-3.0/trackertestutils/tracker-sandbox

%files bin
%defattr(-,root,root,-)
/usr/bin/tracker3

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Tracker-3.0.typelib
/usr/share/bash-completion/completions/tracker3
/usr/share/dbus-1/services/org.freedesktop.portal.Tracker.service
/usr/share/devhelp/books/Tracker/Tracker.devhelp2
/usr/share/devhelp/books/Tracker/assets/MIT.txt
/usr/share/devhelp/books/Tracker/assets/css/bootstrap-toc.min.css
/usr/share/devhelp/books/Tracker/assets/css/custom_bootstrap.css
/usr/share/devhelp/books/Tracker/assets/css/devhelp.css
/usr/share/devhelp/books/Tracker/assets/css/frontend.css
/usr/share/devhelp/books/Tracker/assets/css/jquery.mCustomScrollbar.min.css
/usr/share/devhelp/books/Tracker/assets/css/prism.css
/usr/share/devhelp/books/Tracker/assets/css/tracker-custom.css
/usr/share/devhelp/books/Tracker/assets/fonts/glyphicons-halflings-regular.eot
/usr/share/devhelp/books/Tracker/assets/fonts/glyphicons-halflings-regular.ttf
/usr/share/devhelp/books/Tracker/assets/images/home.svg
/usr/share/devhelp/books/Tracker/assets/js/anchor.min.js
/usr/share/devhelp/books/Tracker/assets/js/bootstrap-toc.min.js
/usr/share/devhelp/books/Tracker/assets/js/bootstrap.js
/usr/share/devhelp/books/Tracker/assets/js/compare-versions.js
/usr/share/devhelp/books/Tracker/assets/js/jquery.js
/usr/share/devhelp/books/Tracker/assets/js/jquery.mCustomScrollbar.concat.min.js
/usr/share/devhelp/books/Tracker/assets/js/jquery.touchSwipe.min.js
/usr/share/devhelp/books/Tracker/assets/js/language_switching.js
/usr/share/devhelp/books/Tracker/assets/js/lines_around_headings.js
/usr/share/devhelp/books/Tracker/assets/js/mustache.min.js
/usr/share/devhelp/books/Tracker/assets/js/navbar_offset_scroller.js
/usr/share/devhelp/books/Tracker/assets/js/navigation.js
/usr/share/devhelp/books/Tracker/assets/js/prism-autoloader.js
/usr/share/devhelp/books/Tracker/assets/js/prism-core.js
/usr/share/devhelp/books/Tracker/assets/js/prism_autoloader_path_override.js
/usr/share/devhelp/books/Tracker/assets/js/scrollspy.js
/usr/share/devhelp/books/Tracker/assets/js/search.js
/usr/share/devhelp/books/Tracker/assets/js/sitemap.js
/usr/share/devhelp/books/Tracker/assets/js/tag_filtering.js
/usr/share/devhelp/books/Tracker/assets/js/trie.js
/usr/share/devhelp/books/Tracker/assets/js/trie_index.js
/usr/share/devhelp/books/Tracker/assets/js/typeahead.jquery.min.js
/usr/share/devhelp/books/Tracker/assets/js/utils.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-abap.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-abap.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-actionscript.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-actionscript.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-apacheconf.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-apacheconf.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-apl.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-apl.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-applescript.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-applescript.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-asciidoc.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-asciidoc.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-aspnet.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-aspnet.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-autohotkey.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-autohotkey.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-autoit.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-autoit.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bash.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bash.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-basic.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-basic.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-batch.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-batch.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bison.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bison.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-brainfuck.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-brainfuck.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bro.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-bro.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-c.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-c.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-clike.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-clike.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-coffeescript.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-coffeescript.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-core.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-core.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-cpp.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-cpp.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-crystal.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-crystal.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-csharp.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-csharp.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-css-extras.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-css-extras.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-css.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-css.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-d.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-d.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-dart.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-dart.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-diff.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-diff.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-docker.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-docker.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-eiffel.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-eiffel.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-elixir.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-elixir.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-erlang.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-erlang.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-fortran.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-fortran.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-fsharp.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-fsharp.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-gherkin.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-gherkin.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-git.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-git.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-glsl.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-glsl.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-go.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-go.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-groovy.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-groovy.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haml.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haml.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-handlebars.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-handlebars.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haskell.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haskell.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haxe.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-haxe.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-http.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-http.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-icon.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-icon.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-inform7.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-inform7.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ini.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ini.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-j.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-j.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-jade.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-jade.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-java.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-java.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-javascript.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-javascript.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-json.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-json.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-jsx.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-jsx.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-julia.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-julia.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-keyman.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-keyman.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-kotlin.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-kotlin.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-latex.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-latex.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-less.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-less.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-lolcode.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-lolcode.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-lua.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-lua.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-makefile.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-makefile.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-markdown.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-markdown.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-markup.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-markup.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-matlab.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-matlab.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-mel.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-mel.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-mizar.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-mizar.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-monkey.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-monkey.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nasm.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nasm.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nginx.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nginx.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nim.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nim.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nix.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nix.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nsis.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-nsis.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-objectivec.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-objectivec.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ocaml.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ocaml.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-oz.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-oz.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-parigp.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-parigp.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-parser.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-parser.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-pascal.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-pascal.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-perl.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-perl.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-php-extras.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-php-extras.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-php.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-php.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-powershell.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-powershell.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-processing.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-processing.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-prolog.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-prolog.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-protobuf.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-protobuf.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-puppet.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-puppet.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-pure.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-pure.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-python.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-python.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-q.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-q.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-qore.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-qore.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-r.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-r.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rest.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rest.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rip.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rip.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-roboconf.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-roboconf.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ruby.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-ruby.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rust.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-rust.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sas.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sas.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sass.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sass.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scala.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scala.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scheme.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scheme.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scss.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-scss.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-smalltalk.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-smalltalk.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-smarty.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-smarty.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sparql.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sparql.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sql.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-sql.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-stylus.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-stylus.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-swift.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-swift.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-tcl.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-tcl.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-textile.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-textile.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-turtle.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-turtle.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-twig.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-twig.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-typescript.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-typescript.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-verilog.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-verilog.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-vhdl.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-vhdl.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-vim.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-vim.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-wiki.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-wiki.min.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-yaml.js
/usr/share/devhelp/books/Tracker/assets/prism_components/prism-yaml.min.js
/usr/share/devhelp/books/Tracker/assets/templates/base_page.html
/usr/share/devhelp/books/Tracker/assets/templates/brand-logo.html
/usr/share/devhelp/books/Tracker/assets/templates/enum_member.html
/usr/share/devhelp/books/Tracker/assets/templates/extra_head.html
/usr/share/devhelp/books/Tracker/assets/templates/field_detail.html
/usr/share/devhelp/books/Tracker/assets/templates/footer.html
/usr/share/devhelp/books/Tracker/assets/templates/member_list.html
/usr/share/devhelp/books/Tracker/assets/templates/multi_return_value.html
/usr/share/devhelp/books/Tracker/assets/templates/navbar.html
/usr/share/devhelp/books/Tracker/assets/templates/navbar_center.html
/usr/share/devhelp/books/Tracker/assets/templates/navbar_links.html
/usr/share/devhelp/books/Tracker/assets/templates/page_content.html
/usr/share/devhelp/books/Tracker/assets/templates/parameter_detail.html
/usr/share/devhelp/books/Tracker/assets/templates/parameters.html
/usr/share/devhelp/books/Tracker/assets/templates/return_item.html
/usr/share/devhelp/books/Tracker/assets/templates/scripts.html
/usr/share/devhelp/books/Tracker/assets/templates/site_navigation.html
/usr/share/devhelp/books/Tracker/assets/templates/stylesheets.html
/usr/share/devhelp/books/Tracker/assets/templates/subpages.html
/usr/share/devhelp/books/Tracker/assets/theme.json
/usr/share/devhelp/books/Tracker/base-ontology.html
/usr/share/devhelp/books/Tracker/dc-ontology.html
/usr/share/devhelp/books/Tracker/defining-ontologies.html
/usr/share/devhelp/books/Tracker/examples.html
/usr/share/devhelp/books/Tracker/gi-index.html
/usr/share/devhelp/books/Tracker/images/icon-fulltextindexed.svg
/usr/share/devhelp/books/Tracker/images/icon-multivalue.svg
/usr/share/devhelp/books/Tracker/images/icon-notify.svg
/usr/share/devhelp/books/Tracker/images/icon-superproperty.svg
/usr/share/devhelp/books/Tracker/images/triple-graph-1.png
/usr/share/devhelp/books/Tracker/images/triple-graph-2.png
/usr/share/devhelp/books/Tracker/images/triple-graph-3.png
/usr/share/devhelp/books/Tracker/implementation.html
/usr/share/devhelp/books/Tracker/index.html
/usr/share/devhelp/books/Tracker/limits.html
/usr/share/devhelp/books/Tracker/mfo-ontology.html
/usr/share/devhelp/books/Tracker/migrating-2to3.html
/usr/share/devhelp/books/Tracker/nao-ontology.html
/usr/share/devhelp/books/Tracker/nco-ontology.html
/usr/share/devhelp/books/Tracker/nepomuk.html
/usr/share/devhelp/books/Tracker/nfo-ontology.html
/usr/share/devhelp/books/Tracker/nie-ontology.html
/usr/share/devhelp/books/Tracker/nmm-ontology.html
/usr/share/devhelp/books/Tracker/nrl-ontology.html
/usr/share/devhelp/books/Tracker/ontologies.html
/usr/share/devhelp/books/Tracker/osinfo-ontology.html
/usr/share/devhelp/books/Tracker/overview.html
/usr/share/devhelp/books/Tracker/performance.html
/usr/share/devhelp/books/Tracker/rdf-ontology.html
/usr/share/devhelp/books/Tracker/rdfs-ontology.html
/usr/share/devhelp/books/Tracker/slo-ontology.html
/usr/share/devhelp/books/Tracker/sparql-and-tracker.html
/usr/share/devhelp/books/Tracker/sparql-functions.html
/usr/share/devhelp/books/Tracker/tracker-batch.html
/usr/share/devhelp/books/Tracker/tracker-endpoint-dbus.html
/usr/share/devhelp/books/Tracker/tracker-endpoint-http.html
/usr/share/devhelp/books/Tracker/tracker-endpoint.html
/usr/share/devhelp/books/Tracker/tracker-misc.html
/usr/share/devhelp/books/Tracker/tracker-namespace-manager.html
/usr/share/devhelp/books/Tracker/tracker-notifier.html
/usr/share/devhelp/books/Tracker/tracker-ontologies.html
/usr/share/devhelp/books/Tracker/tracker-ontology.html
/usr/share/devhelp/books/Tracker/tracker-resource.html
/usr/share/devhelp/books/Tracker/tracker-sparql-connection.html
/usr/share/devhelp/books/Tracker/tracker-sparql-cursor.html
/usr/share/devhelp/books/Tracker/tracker-sparql-error.html
/usr/share/devhelp/books/Tracker/tracker-sparql-statement.html
/usr/share/devhelp/books/Tracker/tracker-uri.html
/usr/share/devhelp/books/Tracker/tracker-version.html
/usr/share/devhelp/books/Tracker/tutorial.html
/usr/share/devhelp/books/Tracker/xsd-ontology.html
/usr/share/gir-1.0/*.gir
/usr/share/tracker3/ontologies/nepomuk/30-nie.description
/usr/share/tracker3/ontologies/nepomuk/30-nie.ontology
/usr/share/tracker3/ontologies/nepomuk/31-nao.description
/usr/share/tracker3/ontologies/nepomuk/31-nao.ontology
/usr/share/tracker3/ontologies/nepomuk/32-nco.description
/usr/share/tracker3/ontologies/nepomuk/32-nco.ontology
/usr/share/tracker3/ontologies/nepomuk/33-nfo.description
/usr/share/tracker3/ontologies/nepomuk/33-nfo.ontology
/usr/share/tracker3/ontologies/nepomuk/38-nmm.description
/usr/share/tracker3/ontologies/nepomuk/38-nmm.ontology
/usr/share/tracker3/ontologies/nepomuk/41-mfo.description
/usr/share/tracker3/ontologies/nepomuk/41-mfo.ontology
/usr/share/tracker3/ontologies/nepomuk/90-tracker.description
/usr/share/tracker3/ontologies/nepomuk/90-tracker.ontology
/usr/share/tracker3/ontologies/nepomuk/92-slo.description
/usr/share/tracker3/ontologies/nepomuk/92-slo.ontology
/usr/share/tracker3/ontologies/nepomuk/93-libosinfo.description
/usr/share/tracker3/ontologies/nepomuk/93-libosinfo.ontology
/usr/share/tracker3/stop-words/stopwords.cs
/usr/share/tracker3/stop-words/stopwords.da
/usr/share/tracker3/stop-words/stopwords.de
/usr/share/tracker3/stop-words/stopwords.en
/usr/share/tracker3/stop-words/stopwords.es
/usr/share/tracker3/stop-words/stopwords.fi
/usr/share/tracker3/stop-words/stopwords.fr
/usr/share/tracker3/stop-words/stopwords.hu
/usr/share/tracker3/stop-words/stopwords.it
/usr/share/tracker3/stop-words/stopwords.nb
/usr/share/tracker3/stop-words/stopwords.nl
/usr/share/tracker3/stop-words/stopwords.pt
/usr/share/tracker3/stop-words/stopwords.ru
/usr/share/tracker3/stop-words/stopwords.sv
/usr/share/vala/vapi/tracker-sparql-3.0.deps
/usr/share/vala/vapi/tracker-sparql-3.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/tracker-3.0/libtracker-sparql/tracker-batch.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-connection.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-cursor.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-endpoint-dbus.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-endpoint-http.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-endpoint.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-error.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-namespace-manager.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-notifier.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-ontologies.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-resource.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-sparql-enum-types.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-sparql.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-statement.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-utils.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-version-generated.h
/usr/include/tracker-3.0/libtracker-sparql/tracker-version.h
/usr/lib64/libtracker-sparql-3.0.so
/usr/lib64/pkgconfig/tracker-sparql-3.0.pc
/usr/lib64/pkgconfig/tracker-testutils-3.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtracker-sparql-3.0.so.0
/usr/lib64/libtracker-sparql-3.0.so.0.200.0
/usr/lib64/tracker-3.0/libtracker-remote-soup2.so
/usr/lib64/tracker-3.0/libtracker-remote-soup3.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/tracker-xdg-portal-3
/usr/libexec/tracker3/endpoint
/usr/libexec/tracker3/export
/usr/libexec/tracker3/help
/usr/libexec/tracker3/import
/usr/libexec/tracker3/sparql
/usr/libexec/tracker3/sql

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tracker/33fabce185708a9b17df7a9f37c7ed44eddc7e48
/usr/share/package-licenses/tracker/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/tracker-xdg-portal-3.service

%files locales -f tracker3.lang
%defattr(-,root,root,-)

